// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPqH5qfK6yZ1XgTYD2M_j7DZAvrr5UizM',
    appId: '1:434585628561:web:7077c6a7ac761a5838b430',
    messagingSenderId: '434585628561',
    projectId: 'trackify-8bc8a',
    authDomain: 'trackify-8bc8a.firebaseapp.com',
    storageBucket: 'trackify-8bc8a.firebasestorage.app',
    measurementId: 'G-DNF20SRH1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvxhZPkuXACm4H9Yjen4FlufZenPERgqk',
    appId: '1:434585628561:android:554f013942b1171338b430',
    messagingSenderId: '434585628561',
    projectId: 'trackify-8bc8a',
    storageBucket: 'trackify-8bc8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzZcZc_eMyqEtNp5j7lWBYAWHP-xVyONw',
    appId: '1:434585628561:ios:9f81cb4a32454d3038b430',
    messagingSenderId: '434585628561',
    projectId: 'trackify-8bc8a',
    storageBucket: 'trackify-8bc8a.firebasestorage.app',
    iosBundleId: 'com.example.trackify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzZcZc_eMyqEtNp5j7lWBYAWHP-xVyONw',
    appId: '1:434585628561:ios:9f81cb4a32454d3038b430',
    messagingSenderId: '434585628561',
    projectId: 'trackify-8bc8a',
    storageBucket: 'trackify-8bc8a.firebasestorage.app',
    iosBundleId: 'com.example.trackify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPqH5qfK6yZ1XgTYD2M_j7DZAvrr5UizM',
    appId: '1:434585628561:web:70b9789d06622e9638b430',
    messagingSenderId: '434585628561',
    projectId: 'trackify-8bc8a',
    authDomain: 'trackify-8bc8a.firebaseapp.com',
    storageBucket: 'trackify-8bc8a.firebasestorage.app',
    measurementId: 'G-4KY9Z1V78D',
  );
}
